name: Actions-Reply
on:
  schedule:
    - cron: 0 1,4,8,10,12,23 * * *
  watch:
    types: [started]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Reply
        env:
          BDUSS: ${{ secrets.BDUSS }}
          TELEGRAM_APITOKEN: ${{ secrets.TELEGRAM_APITOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER_REPO: ${{ secrets.OWNER_REPO }}
          REPLY: ${{ secrets.REPLY }}
        run: go run main.go -cronType re 
